spring:
  application:
    name: post-relay
server:
  port: 8081
telegram:
  bot-token:
  source-chat-ids: -1003162514413, -1002656029749
  polling-interval-ms: 5000
  timeout-sec: 25

vk:
  access-token:
  user-access-token:
  group-id: 229831803
  api-version: "5.199"

logging:
  level:
    com:
      posysaev:
        socialbridge: DEBUG